
package com.kthree.ws;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerStatus", targetNamespace = "http://ws.kthree.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerStatus {


    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerStatus", targetNamespace = "http://ws.kthree.com/", className = "com.kthree.ws.GetServerStatus")
    @ResponseWrapper(localName = "getServerStatusResponse", targetNamespace = "http://ws.kthree.com/", className = "com.kthree.ws.GetServerStatusResponse")
    @Action(input = "http://ws.kthree.com/ServerStatus/getServerStatusRequest", output = "http://ws.kthree.com/ServerStatus/getServerStatusResponse")
    public boolean getServerStatus();

}
